# Setup
title:               BLOG
tagline:             '개발하면서 기록하기'
description:         '다양한 분야의 개발 공부를 기록하고 복습하기 위해 운영하는 블로그'
url:                 https://rain3321.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Seo Min Woo
  url:               https://github.com/rain3321
  email:             smw123123@naver.com

comments:
  provider:          disqus
  disqus:
    shortname:       rain3321
# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

# Custom vars
version:             1.0.0
google_analytics_id: G-4Z9WSXCFHE
